matrix:
  include:
    - language: go
      go:
        - 1.14.x
        - master
      os:
        - linux
        - osx
      sudo: false
      install: true
      script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.29.0
        - $(go env GOPATH)/bin/golangci-lint run
        - go build -o app

    - language: node_js
      node_js:
        - 13
      cache:
        directories:
          - ./static/goscope/node_modules
      install:
        - cd static/goscope && npm install
      script:
        - ng lint
        - ng build --prod --output-hashing none --base-href /goscope/
