matrix:
  include:
    - language: go
      go:
        - 1.14.x
        - master
      os:
        - linux
        - osx
      sudo: false
      install: true
      script:
        - go build -o app

    - language: node_js
      node_js:
        - 13
      cache:
        directories:
          - ./frontend/node_modules
      install:
        - cd frontend && npm install
      script:
        - npm run build
